### ISSUE TITLE
Ability to save web image even if the web server is not activated

### ISSUE THREAD

**Issue by ccaramel** [gehelem/als#108]
hi,
In order to use an external web server, it would be a great idea to make the web_image.jpg with the stack_image.xxx systematically.
Mostly if ALS is installed on a light machine.
Regards.

**Comment by deufrai** [comment]
Should the index.html file be written to the work folder as well upon ALS startup ?

**Comment by ccaramel** [comment]
for my uses, it is not necessary since I use my own index.html on my own webserver. Generally, I don't know if it is better index.html is generated or not.

**Comment by deufrai** [comment]
We improved this even further and made ALS able to write all web content to a specific folder
