### ISSUE TITLE
[OSX] Unable to select text in session log window

### ISSUE THREAD

**Issue by ccaramel** [gehelem/als#111]
Hi,
I don't know if it is made consciously, but currently I cannot select text in session log window.
(using venv on OSX).
It would be useful for debug sharings ;-)

regards.

**Comment by deufrai** [comment]
Hi and thanks for this report
This is an OSX specific issue and will be looked into

As a temporary workaround, you can find logs written into a file named als.log located in your home directory

**Comment by deufrai** [comment]
Worked around this so it works on all platform
Click any log line. ALS puts its content to the system clipboard
