### ISSUE TITLE
Nightly builds don't work on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by DerPit** [gehelem/als#116]
I'm running openSUSE Tumbleweed.  I tried first the nightly builds, but they segfault due to some fontconfig problem (TW has fontconfig-2.13.1):

`woodstock:~% ./als-0.7-dev-77e1b4e.run 
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
.....
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
Fontconfig error: Cannot load config file from /etc/fonts/fonts.conf
Fontconfig warning: FcPattern object weight does not accept value [0 205)
Segmentation fault (core dumped)`

(I also tried an old Leap 42.3 system, but there the glibc is too old.  Not an issue, as the system is out of support anyhow)

**Comment by deufrai** [comment]
Now we are in trouble
![image](https://user-images.githubusercontent.com/1608988/81475058-f3bf8f80-9209-11ea-9d29-cf18bd0f66d4.png)

I just got the latest nightly build into a freshly installed tumbleweed (as a VirtualBox VM) and it starts properly

I do get the fontconfig errors in the terminal, but ALS launches nonetheless

Could you provide the core file your crash generated ?

**Comment by DerPit** [comment]
Now that's weird indeed.  I disabled coredumplimit.  Running it (latest build) generated two coredumps.  You can find them in http://www.sst.iac.es/Downloads/ALS/.
I also tried running it via gdb, but the BT probably isn't too helpful w/o symbols...

`
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7dceea1 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: zypper install libz1-debuginfo-1.2.11-13.1.x86_64
(gdb) bt
#0  0x00007ffff7dceea1 in raise () from /lib64/libc.so.6
#1  0x000000000040532c in ?? ()
#2  0x0000000000403140 in ?? ()
#3  0x00007ffff7db9ceb in __libc_start_main () from /lib64/libc.so.6
#4  0x0000000000401a6e in ?? ()
`

**Comment by deufrai** [comment]
I get HTTP/403 errors trying to download the core dumps

**Comment by DerPit** [comment]
Frederic CORNU wrote:
> I get HTTP/403 errors trying to download the core dumps

Ah sorry.  Bloody default permissions from systemd...
Should work now.

**Comment by deufrai** [comment]
Yep
Got them
I'll see what I can come up with
Thanks !

**Comment by xsnrg** [comment]
If this helps, I also get a core dump trying to run the latest nightly.  Here is my gdb output:

```
[New LWP 288433]
Core was generated by `./als-0.7-dev-c1bdb51.run'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;

```
This is on Fedora 32.

**Comment by deufrai** [comment]
@DerPit in order to eliminate a potential issue on your end, i just built an ALS executable on my fresh tumbleweed. It is available here : https://als-app.org/assets/support/issue_116/
Could you try and run it on your machine ?
Thanks in advance

**Comment by DerPit** [comment]
Frederic CORNU wrote:
> @DerPit in order to eliminate a potential issue on your end, i just built an ALS executable on my fresh tumbleweed. It is available here : https://als-app.org/assets/support/issue_116/
> Could you try and run it on your machine ?

Thanks Frederic!

I just downloaded it, and this indeed starts without any errors.
Testing functionality will take more time, I'm at work ATM...

**Comment by DerPit** [comment]
> If this helps, I also get a core dump trying to run the latest nightly. 
> 
> This is on Fedora 32.

I wonder if that TW build (also) runs on your machine.  I think TW and Fedora 32 are quite similar in what libs etc. they use?

**Comment by deufrai** [comment]
> Frederic CORNU wrote:
> @DerPit in order to eliminate a potential issue on your end, i just built an ALS executable on my fresh tumbleweed. It is available here : https://als-app.org/assets/support/issue_116/ Could you try and run it on your machine ?
> Thanks Frederic! I just downloaded it, and this indeed starts without any errors. Testing functionality will take more time, I'm at work ATM...

Good news in a way : you'll get to play with it.
On another hand, that does not help us understand why a nightly runs on my tumbleweed and not on yours...

Digging deeper whith what you provided
Stay tuned

**Comment by xsnrg** [comment]
@deufrai I verified the special build you created for @DerPit also works for me on Fedora32.

**Comment by deufrai** [comment]
Couldn't get much more info from the provided dumps
The only workaround I can think of for now is build from sources using pyenv to get a 3.6.x or 3.7.x python that allows you guys to get all needed dependencies

**Comment by deufrai** [comment]
please reopen if still occurring
