### ISSUE TITLE
pip doesn't find the packages requested by requirements.txt (Invalid)

### ISSUE THREAD

**Issue by DerPit** [gehelem/als#117]
I tried to follow the installation instructions in README.rst, to install ALS on my openSUSE Tumbleweed system, doing a git install  (I cloned the master branch).
I executed (part of) the instructions in ./utils/venv_setup.sh manually, as the shellscript only works for Debian/*buntu systems.
Generating the virtual environment succeeded, but when I wanted to install the requirements,
pip install -r requirements.txt, it failed to locate opencv-python in the requested version.

While writing this, I realized the problem is the python version, TW is already at Python 3.8.2.  Not sure if there's an easy way to get ALS running with the newer version?

**Comment by deufrai** [comment]
hi
Most of our dependencies (in their specified versions) are not kept up to date on PyPi for python 3.8. 

We'll have to test ALS with newer versions of those libs, but it is a touchy business and won't be completed soon.

if you could get a 3.7 version of python using pyenv or any other mean, the install procedure will succeed.

Kepp us posted and thanks for the report

**Comment by deufrai** [comment]
I'm closing this one, as this works as expected when using python 3.6 or 3.7 as stated in the README :)
