### ISSUE TITLE
Supported File Formats

### ISSUE THREAD

**Issue by WirthmU** [gehelem/als#128]
Is there a list of all supported input file types (eg raw, jpeg, etc.)?

**Comment by deufrai** [comment]
yup, second line of the readme file :) :

> ALS is compatible with .fit and .fits files and RAW camera files : https://www.libraw.org/supported-cameras

**Comment by deufrai** [comment]
I agree this could be better phrased

**Comment by WirthmU** [comment]
I am using the new Raspberry Pi HQ camera. The RPI's are on the list.

What would be the raspistill (or raspiyuv) command to get pictures that are compatible with als?

**Comment by deufrai** [comment]
sorry, I don't have the slightest idea

**Comment by deufrai** [comment]
closing : userguide & website rework will cover this
