### ISSUE TITLE
When stacking starts it crashes

### ISSUE THREAD

**Issue by iooo64** [gehelem/als#132]
When stacking starts it crashes

2020-09-26 09:20:33,317 Dummy-4      als.processing       INFO     Start stack on FILE : /home/marekb/als/scan/Light_002.fits
Traceback (most recent call last):
  File "/home/marekb/Downloads/als/src/als/code_utilities.py", line 39, in wrapped
    result = func(*args, **kwargs)
  File "/home/marekb/Downloads/als/src/als/processing.py", line 606, in run
    self._handle_image(image)
  File "/home/marekb/Downloads/als/src/als/code_utilities.py", line 39, in wrapped
    result = func(*args, **kwargs)
  File "/home/marekb/Downloads/als/src/als/stack.py", line 171, in _handle_image
    self._align_image(image)
  File "/home/marekb/Downloads/als/src/als/code_utilities.py", line 39, in wrapped
    result = func(*args, **kwargs)
  File "/home/marekb/Downloads/als/src/als/stack.py", line 203, in _align_image
    self._apply_transformation(image, transformation)
  File "/home/marekb/Downloads/als/src/als/code_utilities.py", line 39, in wrapped
    result = func(*args, **kwargs)
  File "/home/marekb/Downloads/als/src/als/stack.py", line 246, in _apply_transformation
    image.data[channel] = data
ValueError: could not broadcast input array from shape (2,1200,1920) into shape (1200,1920)
Neúspěšně ukončen (SIGABRT) (core dumped [obraz paměti uložen])
![Screenshot_20200926_091116](https://user-images.githubusercontent.com/19565168/94346760-13c3e400-002f-11eb-809b-bf85188976a2.png)
![Screenshot_20200926_091116](https://user-images.githubusercontent.com/19565168/94346765-1aeaf200-002f-11eb-83ce-6b58583ac649.png)
![Screenshot_20200926_091116](https://user-images.githubusercontent.com/19565168/94346774-250cf080-002f-11eb-9130-680a27b4fc97.png)
![foo](https://user-images.githubusercontent.com/19565168/94346777-2b9b6800-002f-11eb-90a3-cbb5c3374252.png)

**Comment by deufrai** [comment]
Hi and thanks for the report

Could you please share at least 2 images from that imaging session ?

**Comment by iooo64** [comment]
Yes

[FITS.zip](https://github.com/gehelem/als/files/5287124/FITS.zip)

**Comment by deufrai** [comment]
could not reproduce the issue.
The log you provided seems to tell us the issue may be the first image. Could you share image #1, pease ?

**Comment by iooo64** [comment]
It happens always regardless of the order of fits. I did try several different FITS and the error always happens. Now I tested Light_002.fits and then Light_003.fits from the uploaded FITS.zip and the result is the same. May it be related to a specific version of some Python package? And if so, which could be it?

Here is the output of the pip list command:

alabaster                     0.7.12
als                           0.7a2.post0.dev7+gde1d122 /home/marekb/Downloads/als/src
anytree                       2.8.0
apparmor                      2.13.4
appdirs                       1.4.4
asn1crypto                    1.4.0
astroalign                    2.1
astroid                       2.4.2
astroplan                     0.6
astropy                       4.0.1
attrs                         19.3.0
Automat                       20.2.0
Babel                         2.8.0
backcall                      0.2.0
Beaker                        1.11.0
beautifulsoup4                4.9.1
breezy                        3.1.0
Brlapi                        0.7.0
btrfsutil                     1.2.0
CacheControl                  0.12.6
ceph-volume                   1.0.0
cephfs                        2.0.0
cephfs-shell                  0.0.1
certifi                       2020.6.20
cffi                          1.14.2
chardet                       3.0.4
click                         7.1.2
colorama                      0.4.3
configobj                     5.0.6
constantly                    15.1.0
contextlib2                   0.6.0.post1
cryptography                  3.0
cycler                        0.10.0
decorator                     4.4.2
diskcache                     4.1.0
distlib                       0.3.1
distro                        1.5.0
docutils                      0.16
FoxDot                        0.8.11
future                        0.18.2
gmusicapi                     12.1.1
gps                           3.21
gpsoauth                      0.4.1
gpymusic                      1.2.1
h5py                          2.10.0
html5lib                      1.1
httplib2                      0.17.0
hyperlink                     20.0.1
idna                          2.10
imageio                       2.9.0
imagesize                     1.2.0
incremental                   17.5.0
ipython                       7.17.0
ipython-genutils              0.1.0
isc                           2.0
isodate                       0.6.0
isort                         5.2.2
jedi                          0.17.0
Jinja2                        2.11.2
jplephem                      2.14
kazam                         1.4.5
kiwisolver                    1.2.0
lazy-object-proxy             1.5.1
lensfun                       0.3.95
LibAppArmor                   2.13.4
libmsym                       0.2.4
libvirt-python                6.4.0
lockfile                      0.12.2
Logbook                       1.5.3
louis                         3.14.0
lxml                          4.5.2
lz4                           2.2.1
Mako                          1.1.3
Markdown                      3.2.2
markdown2                     2.3.9
MarkupSafe                    1.1.1
matplotlib                    3.3.1
mccabe                        0.6.1
MechanicalSoup                0.12.0
mercurial                     5.5
meson                         0.55.1
mock                          4.0.1
mpld3                         0.3
mps-youtube                   0.2.8
msgpack                       1.0.0
mutagen                       1.43.1
netifaces                     0.10.9
networkx                      2.5
numpy                         1.19.1
oauth2client                  4.1.3
ordered-set                   4.0.2
packaging                     20.4
pafy                          0.5.5
parso                         0.8.0
pathtools                     0.1.2
patiencediff                  0.2.0
pep517                        0.8.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        7.2.0
pip                           20.1.1
ply                           3.11
proboscis                     1.2.6.0
progress                      1.5
prompt-toolkit                3.0.6
protobuf                      3.11.3
protontricks                  1.4.1
psutil                        5.7.2
ptyprocess                    0.6.0
pulsemixer                    1.5.1
pwquality                     1.4.2
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pybind11                      2.5.0
pycairo                       1.19.1
pycodestyle                   2.6.0
pycparser                     2.20
pycryptodomex                 3.9.7
pyflakes                      2.2.0
Pygments                      2.6.1
PyGObject                     3.36.1
PyHamcrest                    1.9.0
pyinotify                     0.9.6
pyliblo                       0.10.0
pylint                        2.5.3
PyOpenGL                      3.1.5
pyparsing                     2.4.7
Pypubsub                      4.0.3
PyQt5                         5.15.0
PyQt5-sip                     12.8.0
python-dateutil               2.8.1
python-distutils-extra        2.39
python-pam                    1.8.4
python-xapp                   2.0.0
python-xlib                   0.27
pytoml                        0.1.21
pytz                          2020.1
PyWavelets                    1.1.1
pyxdg                         0.26
PyYAML                        5.3.1
qimage2ndarray                1.8.3
QtPy                          1.9.0
rados                         2.0.0
rawpy                         0.15.0
rbd                           2.0.0
rdflib                        5.0.0
rencode                       1.0.6
requests                      2.24.0
resolvelib                    0.4.0
retrying                      1.3.3
rgw                           2.0.0
roman                         3.3
rpm                           4.15.1
rsa                           4.0
scikit-image                  0.17.2
scipy                         1.4.0
sep                           1.0.3
setproctitle                  1.1.10
setuptools                    49.6.0
simplejson                    3.17.2
sip                           4.19.23
six                           1.15.0
snowballstemmer               2.0.0
soupsieve                     2.0.1
Sphinx                        3.2.1
sphinx-rtd-theme              0.5.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
SQLAlchemy                    1.3.19
team                          1.0
tifffile                      2020.9.22
tinycss2                      1.0.2
toml                          0.10.1
traitlets                     4.3.3
trash-cli                     0.17.1.14
Twisted                       20.3.0
urllib3                       1.25.10
validictory                   1.1.2
vdf                           3.3
watchdog                      0.10.3
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.35.1
wrapt                         1.12.1
wxPython                      4.0.7.post2
xpra                          3.0.9
youtube-dl                    2020.7.28
zope.interface                5.1.0

**Comment by deufrai** [comment]
Good catch
Specifc library versions can behave unexpectedly
That's why we have a requirement file

Did you compare the versions in your listing with the content of our 'requirements.txt' file ?

**Comment by iooo64** [comment]
Thank you very much. I installed packages versions based on  requirements.txt file and everything works fine. I'm sorry, I didn't notice existence of this file. So problem soved.

**Comment by deufrai** [comment]
Nice
Have a good time with ALS
