### ISSUE TITLE
Minimum System Requirements?

### ISSUE THREAD

**Issue by buzkill420** [gehelem/als#143]
Can't seem to find any min specs or usage statistics. Any info would be much appreciated.

**Comment by gehelem** [comment]
Hi
Does requirements.txt file answers your question ?
G.

**Comment by Steffou** [comment]
Hi, we made few tests more than a year ago, with 3 different hardware plateformes, all with Linux.
RPI4, Up!Board (Atom X5), and a Classical Laptop (I7@2.2GHz)

These tests were for the complete process per new image. We seen that ALS running on a RPI4 for live stacking on EAA for example,  seems to be ok for little camera, but not with a full frame. 
With a laptop, a fullframe image is completely stack and processed every 10/15s.

**Comment by deufrai** [comment]
Will be detailed in #165
