### ISSUE TITLE
Wrong Bayer Pattern detected

### ISSUE THREAD

**Issue by Robowarrior834** [gehelem/als#153]
I have it set to auto and it is trying to use GBRG for a Canon 5D MK ii. Canon uses RGGB for the pattern.

**Comment by deufrai** [comment]
Hi and thanks for the report

A workaround for this is to set the Bayer pattern to be used, in the preferences panel

If you could provide a .CR2 file from your DSLR, that would be great

**Comment by Robowarrior834** [comment]
https://drive.google.com/file/d/1Bxra-NfZ4rAE3DwLdBh1hzLlD-q6U3LX/view?usp=sharing

**Comment by deufrai** [comment]
Hey

Long time no see...

Canon 5D MKii indeed uses a RGGB pattern, but the library (LibRaw) ALS uses for reading RAW files made changes and several Canon cameras are now seen as using a GBRG pattern

Pixinsight, which also uses LibRaw got reports of the same type. See: https://pixinsight.com/forum/index.php?threads/debayer-problems-canon-5d-mark-ii.14910/

Thanks for providing a file of yours. 

I opened it with both Pixinsight and ALS. It indeed is seen as GBRG and is looks correctly debayered when we let the software use the detected pattern

See below a comparison done in ALS between Left : AUTO=GBRG and Right : MANUAL=RGGB
Auto mode clearly outputs the image as it should be, when manual mode provides a green dominated image.

![image](https://github.com/user-attachments/assets/fc0cb285-0ac0-493e-8acd-72eccf0da7f7)

Zooming further into the image debayered with forced RGGB shows a grid artifact, implying that RGGB is not the right pattern to use.

![image](https://github.com/user-attachments/assets/93df1650-044d-4284-8b92-a5c65d372775)

even though it clashes with reality, GBRG is in this context the right pattern to use. And ALS debayer pattern needs to be kept in Auto with .CR2 files shot with a Canon 5D Mkii

Thanks and clear skies :)
