### ISSUE TITLE
web site ALS

### ISSUE THREAD

**Issue by Josefino** [gehelem/als#155]
This web site https://als-app.org/nightlies  is not available.

**Comment by deufrai** [comment]
issue is fixed, now

Thank you very much for reporting it. Faulty monitoring will be improved/fixed as well

May 2022 bring you clear skies !

**Comment by Josefino** [comment]
Great!!! Thank you very much!

Clear sky!

Josef

ne 2. 1. 2022 v 12:01 odesílatel Frederic CORNU ***@***.***>
napsal:
