### ISSUE TITLE
Strange color pattern in stacking 

### ISSUE THREAD

**Issue by fuherb** [gehelem/als#169]
Hi, extremely delighted to see a lot of prgress in ALS lately.  Thanks a lot.

Previously I reported a number of issues $158 and $167.

I downloaded the latest nightly build 0ebcfa6 linux 64 bit version to try.  I have to say that it works great, even the DNG files from the Raspberry Pi is read successfully.

I do notice however a strange color effect in the stacked image,  A screenshoot is attached.  There are chessboard pattern of colors shown.  Too big for Debayer defects so I do not know what they are.
![Screenshot at 2023-03-06 09-59-09](https://user-images.githubusercontent.com/97459579/223003932-711fd935-c52a-46c3-8c9b-980d0777797b.png)

**Comment by deufrai** [comment]
Hi

as always, thanks for the report.

colorful patches can be expected after reading a single file (as shown on your screenshot : Stack size = 1)
Are those patches still present after a few more frames added to the stack ?

If yes, I'd like you to somehow share at least 5 of your frames so I can investigate

**Comment by deufrai** [comment]
and if you see those patterns disappear when changing zoom factor, so that's just a side effect of the way the image is presented in the central area

whe had to choose between seed and accuracy.

Room for improvement there, for sure

**Comment by fuherb** [comment]
Thanks for quick response.  One good new and one bad news.

I tried to stack a few more images and the color pattern fades away as you have anticipated.  I believe this is not an issue anymore.  Then so far I try the new release in my desktop PC which is old (5-6 years) but decent.

Then I install the new release in my netbook (12 years old Intel Atom based) which is the real working unit in the field.  Then again it hanged when the second image was loaded.  I attached a log file for your reference.  I believe to run ALS you do need a certain minimum specification.  I can't upload the image files for your ref as DNG is not supported.
[als.log](https://github.com/gehelem/als/files/10895417/als.log)

**Comment by deufrai** [comment]
Thanks for the log upload.
By default, they don't give much information regarding issues.

When you have a chance : please reproduce the issue after having enabled the 'details logs' in ALS preferences (this needs an ALS restart)

Thanks in advance

**Comment by fuherb** [comment]
Thanks

I redo it.  Crash essentially like the first time with the second image file.  The first file launch is the one with "no_9" in the file name.  The second one is "no_8".  The debug log is very detailed and I hope this will throw in some insight.  Still you can see the netbook take many seconds to process the first image so that might be too weak.
[als02.log](https://github.com/gehelem/als/files/10896165/als02.log)

**Comment by deufrai** [comment]
ok, 2 more things to go further :

1. does ALS crash (close itself) or just stop stacking ?
2. if it crashes, could you try and launch ALS from within a terminal then reproduce the issue ? there may be an explicit error message or stack trace, there

**Comment by fuherb** [comment]
It just stop working, the mouse freeze, the hard drive LED light up continuously.  It does not close.  I will try to run from terminal then.

**Comment by fuherb** [comment]
Well, it is a bit confusing.

First, I try to stack these images once again in the ALS in desktop PC to confirm that they are upto the standard to be stacked in ALS.  They are OK.

Then, I start ALS in netbook from terminal.  The strange thing is ALS rejects the images for stacking for whatever reasons.  So this time it does not hang up and simply not stacking (but these images are stacked in Desktop successfully).  Nevertheless I enclosed the log file als03.log.  Looking into the terminal, the info are exactly the same as the log file.  Nothing additional.

Then I rerun just by double clicking in netbook.  As expected, it hang when the second images run into color alignment.
[als03.log](https://github.com/gehelem/als/files/10896941/als03.log)

**Comment by deufrai** [comment]
PLease test with a special build that might solve the issue on the netbook :
https://als-app.org/assets/support/issue_169/

**Comment by fuherb** [comment]
Wow, great support.  

Tried in netbook, it moved 1 step forward.  Previously it hanged with the number of stack stayed at 1.  This time the digit advanced to 2, but then it hanged again.  log file attached. 
[als04.log](https://github.com/gehelem/als/files/10897496/als04.log)

**Comment by deufrai** [comment]
It seems to choke on the autostretch process for the second image.... 

Is there a way for you to upload a handful of your DNG files somewhere online where I could grab them ?
That would ease up pinpointing the real issue

**Comment by fuherb** [comment]
I send you an email with images.  Please see if you can get them.

**Comment by fuherb** [comment]
Send you 4 emails with 1 sample per mail

**Comment by deufrai** [comment]
managed to stack them on Linux in here.
maybe a resources issue, I can see that your netbook is quite low on memory on ALS startup and on following image reads :

```
2023-03-06 18:46:33,664 MainThread   __main__             DEBUG    Available memory      : 398.438 MiB
2023-03-06 18:47:29,954 Dummy-1      als.processing       DEBUG    Available system memory : 351.840 MiB
2023-03-06 18:48:00,019 Dummy-1      als.processing       DEBUG    Available system memory : 217.035 MiB
```

please try and launch that very same 'special version' : 0.7-dev-4a27b8c in a terminal. Hoping for details that didn't make it to the logs...

**Comment by fuherb** [comment]
Yes, my Desktop runs linux Mint and everything works OK so far, the issue is with the netbook so resource limitation can be the main problem.

I run in terminal the special version in the netbook, the 2nd image is rejected this time, and the 3rd image seemed to have been stacked, but again choke in auto-stretch.  Log file attached.

I am currently running this netbook for EAA using ASTAP live stacking.  That is working OK, slow of course but never hang up or crash.  Maybe he took a very different approach in handling the images.  Frankly I would like to use ALS as this is a dedicated live stacking software, and the UI fit EAA better.  But if resources is an issue, the only way out is to find a better notebook computer.
[als05.log](https://github.com/gehelem/als/files/10898333/als05.log)

**Comment by fuherb** [comment]
Ah, missed the point.  The terminal did not show any additional info compared to the log.  As a matter of fact, less info

**Comment by fuherb** [comment]
Appreciate your effort and support.  I hope I am not taking too much resources from you.

A comment on the failed stacking of th 2nd image mentioned above.  I use the same set of images over and over again to test to avoid any impact due to image variation, that includes the file I sent you.  Hence this "failed" second image had been successfully registered and stacked before (at lteast in the Desktop Linux).  Somehow there can be variation in the registration process so images that are marginally can be registered one time but failed another.  Not sure if this is something that worth some check to enhance the robustness.

The netbook screen height is 600 pixels, essentially the UI window cannot fit into the screen and the log window is invisible to me.  I rely on the log file to check what happened.

Overall I need to admit that I am using an inferior tool to run your program, so it is not all that fair to push the program to work for it.

**Comment by deufrai** [comment]
> The netbook screen height is 600 pixels, essentially the UI window cannot fit into the screen and the log window is invisible to me. I rely on the log file to check what happened.

Then you might be interested in #130 as well

**Comment by fuherb** [comment]
Seems that 0.8 will be an interesting release.  I suppose if the control panels and the display windows are separated, you have a lot more flexibility in the UI.

I have not touched on the webserver yet.  This will be another great feature when I get things straighten out in the netbook (if finally we get it resolved).  Instead of using the UI viewer I think I can just use the browser in the netbook and display the html file.

**Comment by fuherb** [comment]
I would like to report that I apparently get it fixed.  Noting that the low memory can be the principal problem I created a swap file in the hard drive of size 2G.  Then I run the 4a27b8c version in the netbook and I successfully stack 10 images without issues.  Log file attached.  Within days when sky is clear I will try to test in the field.

Remaining concerns might be the robustness of this solution and that if the netbook can handle fast incoming of files (faster than it can process).

Nevertheless it is very good to see a developer so helpful in addressing the issue.  Thanks again.

**Comment by fuherb** [comment]
log file forgottten.
[als06.log](https://github.com/gehelem/als/files/10899947/als06.log)

**Comment by fuherb** [comment]
It is late in Asia now, will try tomorrow. Thanks.

在 2023年3月6日週一 23:48，Frederic CORNU ***@***.***> 寫道：

**Comment by fuherb** [comment]
This morning I test with 0ebcfa6 and it also works.  So the normal release can run on the netbook with the swap file.  attached log for reference.
[als07.log](https://github.com/gehelem/als/files/10904261/als07.log)

**Comment by fuherb** [comment]
I am starting a new thread on running ALS in thin resources.  I think we are already pretty off topic here.

**Comment by deufrai** [comment]
indeed. 
See you there
