### ISSUE TITLE
display accumulated exposure time for current stack

### ISSUE THREAD

**Issue by deufrai** [gehelem/als#173]

**Comment by fuherb** [comment]
Another suggestion: As an overall info set to monitor the live stacking process, I think it will be good to have -
a. No of subs stacked (already exist in current release)
b. No of subs rejected (can help monitor if the image capturing process is running OK)
c. cummulative exposure time (per this thread)

**Comment by deufrai** [comment]
> No of subs rejected (can help monitor if the image capturing process is running OK)
great one

In fact I'm thinking about actually displaying some info about the last alignment process si you can tailor your threshold setting
And nb. or rejected frames is a good point, thanks

**Comment by fuherb** [comment]
Thanks for taking attention.  Moving forward it might be good to consider how to avoid making a very busy UI.  When setting up the live stacking session you might need to be presented with all options.  When the session is running, it's like driving your car you focus only on the dash board and the front view and mirrors.  Only when you notice something required intervention then you turn to the controls.
