### ISSUE TITLE
Can't change scan and work folders under Ubuntu

### ISSUE THREAD

**Issue by Russell797** [gehelem/als#178]
Can not change folders "scan" or "work" in preferences under Ubuntu 22.04. Hitting "Change" immediately crashes the program.
Happens on two separate machines.  Everything works fine if I manually modify the config file to point to new locations however. 

Not an issue running under Kubuntu 22.04 however.

**Comment by deufrai** [comment]
Hi 

sorry for that.
this has to do with your WM icon themes and was already reported several times :(
Thankfully, you found your way into the config file

Be sure we'll eventually find a fix for that 

Closing as duplicate of #156

Clear skies
