### ISSUE TITLE
No such file or directory: 'pyuic5'

### ISSUE THREAD

**Issue by Frankastro85** [gehelem/als#189]
Hello,
I use a RPI 64b.
I installed all the directory : 
![image](https://github.com/gehelem/als/assets/65867903/c880d4d5-05a0-48d5-9d80-e5b134a729dd)

But I've a problem here : 

pi@pi:~/als $ source ./venv/bin/activate
(venv) pi@pi:~/als $ python setup.py develop
Compiling UI files
==================
Executing command : pyuic5 /home/pi/als/src/als/ui/als_ui.ui -o /home/pi/als/src/generated/als_ui.py --import-from=generated
Traceback (most recent call last):
  File "/home/pi/als/setup.py", line 29, in <module>
    compile_ui_and_rc.main()
  File "/home/pi/als/utils/compile_ui_and_rc.py", line 19, in main
    completed_process = subprocess.run([command, ] + args.split(" "))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyuic5'
(venv) pi@pi:~/als $ als
bash: als: command not found

An idea ?
Thank you,
Frank

**Comment by deufrai** [comment]
Hi

pyuic5 is part ff the PyQt5 package. But it is expected to bump into issues when trying to run from sources on a RPI. Especially on a recent 64bits system.

We are currently settings the project back on track after a (too) long inactive period, and our top priority is to provide pre-built releases for 64bits ARM (RPI 4 & 5)

I'll give you some news in this issue when they are available. Stay tuned

**Comment by gehelem** [comment]
Hi
Please have a look here :
[https://www.webastro.net/forums/topic/173188-als-astro-live-stacker/page/9/#comment-3149159]()

**Comment by deufrai** [comment]
to run ALS on a 64 bits Raspberry, please 

1. get this special build : https://als-app.org/assets/custom_builds/als-v0.7-beta2_arm64.tgz
2. extract the downloaded archive whenever you want on your Pi
3. launch the executable named `als-v0.7-beta2`

**Comment by Frankastro85** [comment]
Perfect ! Thank you so much,
Frank

**Comment by deufrai** [comment]
@Frankastro85 would you be so kind to report here when you get a chance to test that version ?
With hardware and OS / Distro details, please :)

That would help us decide if this build is good enough to be published on our GitHub releases.

Many thanks in advance

**Comment by Frankastro85** [comment]
@deufrai Yes, of course, no problem.
The installation is ok on a RPI 4b 64b.
I need to wait to a clear sky to trying.

**Comment by deufrai** [comment]
Hey thanks !
May I ask what Linux distribution and version you are running ?

**Comment by Frankastro85** [comment]
Yes, of course : 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"

Model		: Raspberry Pi 4 Model B Rev 1.1
Aarch64

I'll use with an ASI224MC or 1600MC.

**Comment by deufrai** [comment]
Thanks !

Closing this issue as completed. 
ARM64 archive is now published on our latest release page : https://github.com/gehelem/als/releases/tag/v0.7-beta2
