### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by petmos** [gehelem/als#191]
There have been no more commits for more than a year. The last commit is from March 25, 2023.
And on https://als-app.org/ the current version is 0.6.
It would be nice if the project could be maintained further.

**Comment by deufrai** [comment]
Hey

Past year has been very complicated, but progress is to be expexted soon.
main goalnfornthe next 2 month is to be able to provide Raspberry Pi builds compatible with newer RPI OS version, as well as 64 bit builds. 

Please bare with us, things will imrpove

**Comment by petmos** [comment]
That are wounderful news.
It really is a great tool. Many thanks for it.
With 64 bit builds you mean for RPI or x86_64?

**Comment by deufrai** [comment]
I mean arm64 versions for RPIs running a 64bit OS

All other (windows & linux PCs + Mac) are already 64bit
