### ISSUE TITLE
Is a web version could be possible ?

### ISSUE THREAD

**Issue by HamHamFonFon** [gehelem/als#192]
As seen in https://github.com/gehelem/als/issues/191 i'm happy to see your project is not dead :) .
If installation on RPi is OK and RPi working in remote, do you think think it will be possible to access to ALS with navigator ?

My Rpi with indi and indiwebmanager on it is running in remote. Client-side i'm using kstars ekos and i will use ALS on client-side too. However i prefer to run it server side...

Thank you

**Comment by deufrai** [comment]
Hi

This is deffo planned, as mentioned in #134
But that won't happen soon, as it implies some changes on the 'engine' and smart tech choices on the UI side, + the skills to do it right

Bit this really is the way we want to steer ALS : a headless core with nice web UI

Thanks for asking 

Closing issue as duplicate

**Comment by HamHamFonFon** [comment]
All right !! Good luck for this refactoring, i'll be waiting :)
