### ISSUE TITLE
Pb d'installation sur RasberryPI 5

### ISSUE THREAD

**Issue by jmoucaud** [gehelem/als#193]
J'ai tenté l'install d'ALS sur RAspPI5 ... tout se passe bien jusqu'à l'étape 5 :
Compiling UI files
==================
Executing command : pyuic5 /home/jmoucaud/als/src/als/ui/prefs_ui.ui -o /home/jmoucaud/als/src/generated/prefs_ui.py --import-from=generated
Traceback (most recent call last):
  File "/home/jmoucaud/als/setup.py", line 29, in <module>
    compile_ui_and_rc.main()
  File "/home/jmoucaud/als/utils/compile_ui_and_rc.py", line 19, in main
    completed_process = subprocess.run([command, ] + args.split(" "))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pyuic5'
----------------------------
La commande als ne donne rien !
J'ai bien l'environnement virtuel (venv).
Pouvez-vous m'aider ?
Merci d'avance.

**Comment by deufrai** [comment]
Hello

Nous fournissons de quoi ne pas avoir besoin de tout installer compiler chez soi
C'est par ici => https://github.com/gehelem/als/releases/tag/v0.7-beta2

Pour les PI, il s'agit d'une archive à extraire où tu veux sur ton système. Il n'y a plus qu'à lancer l'exécutable qui se trouve au premier niveau

Tiens nous au jus de la réussite (ou non) de la manoeuvre

**Comment by jmoucaud** [comment]
Bonsoir,
l'installation a fonctionné.
A suivre
Merci beaucoup
JM

Le mar. 6 août 2024 à 20:38, Frederic CORNU ***@***.***> a
écrit :

**Comment by deufrai** [comment]
Good news

**Comment by jmoucaud** [comment]
C'est tout bon. Ça fonctionne.
Merci
JM

Le mar. 6 août 2024 à 21:55, Frederic CORNU ***@***.***> a
écrit :
