### ISSUE TITLE
[New feature ?] Generate QR code for image server url

### ISSUE THREAD

**Issue by gnthibault** [gehelem/als#4]
Do you think it would be a good idea to generate a QR-code from ALS such that one can easily share the url for people to connect to the image server through their phone ?

Using this: https://pypi.org/project/qrcode/ looks not so hard

**Comment by gnthibault** [comment]
Small POCS, very easy and works reliably:

```
import qrcode
import matplotlib.pyplot as plt

qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_L,
    box_size=10,
    border=4,
)
qr.add_data('http://192.168.0.1')
qr.make(fit=True)

img = qr.make_image(fill_color="black", back_color="white")
plt.imshow(img)
plt.show()

```

**Comment by deufrai** [comment]
Done with 0ebcfa676175905405ebfaf2326cf1cf851067f5
