### ISSUE TITLE
Getting errors that prevent the counter from going past 1

### ISSUE THREAD

**Issue by kbahey** [gehelem/als#40]
I am using Xubuntu 18.04 LTS, and installed ALS using the instructions on the Github page.

When I try the samples, I get the following output:

someone@astro:~$ python3 ~/als/als.py 
/home/someone/als/wrk
/home/someone/als/scan
New image arrive: /home/someone/als/scan/Light_1069.fits
The file does not exist
debayering...
TIFF image create : /home/someone/als/wrk/stack_image.tiff
first file created : /home/someone/als/wrk/stack_ref_image.fit
New image arrive: /home/someone/als/scan/Light_1114.fits
debayering...
alignement and stacking...
  0%|                                                     | 0/3 [00:00<?, ?it/s]New image arrive: /home/someone/als/scan/Light_1171.fits
100%|█████████████████████████████████████████████| 3/3 [00:00<00:00,  3.32it/s]
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/imgproc/src/color.cpp, line 9716
Traceback (most recent call last):
  File "/home/someone/als/als.py", line 66, in <lambda>
    align_on, save_on, stack_methode))
  File "/home/someone/als/als.py", line 80, in created
    save_im=save_on, align=align_on, stack_methode=stack_methode)
  File "/home/someone/als/stack.py", line 231, in stack_live
    save_tiff(work_path, np.array(stack_image), mode=mode)
  File "/home/someone/als/stack.py", line 30, in save_tiff
    cv2.imwrite(work_path + "/stack_image.tiff", cv2.cvtColor(new_stack_image, cv2.COLOR_RGB2BGR))
cv2.error: /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/imgproc/src/color.cpp:9716: error: (-215) scn == 3 || scn == 4 in function cvtColor

debayering...
Traceback (most recent call last):
  File "/home/someone/als/als.py", line 66, in <lambda>
    align_on, save_on, stack_methode))
  File "/home/someone/als/als.py", line 80, in created
    save_im=save_on, align=align_on, stack_methode=stack_methode)
  File "/home/someone/als/stack.py", line 158, in stack_live
    raise ValueError("fit format not support")
ValueError: fit format not support
New image arrive: /home/someone/als/scan/Light_1254.fits
debayering...
Traceback (most recent call last):
  File "/home/someone/als/als.py", line 66, in <lambda>
    align_on, save_on, stack_methode))
  File "/home/someone/als/als.py", line 80, in created
    save_im=save_on, align=align_on, stack_methode=stack_methode)
  File "/home/someone/als/stack.py", line 158, in stack_live
    raise ValueError("fit format not support")
ValueError: fit format not support
New image arrive: /home/someone/als/scan/Light_1264.fits
debayering...
Traceback (most recent call last):
  File "/home/someone/als/als.py", line 66, in <lambda>
    align_on, save_on, stack_methode))
  File "/home/someone/als/als.py", line 80, in created
    save_im=save_on, align=align_on, stack_methode=stack_methode)
  File "/home/someone/als/stack.py", line 158, in stack_live
    raise ValueError("fit format not support")
ValueError: fit format not support
New image arrive: /home/someone/als/scan/Light_1283.fits
debayering...
Traceback (most recent call last):
  File "/home/someone/als/als.py", line 66, in <lambda>
    align_on, save_on, stack_methode))
  File "/home/someone/als/als.py", line 80, in created
    save_im=save_on, align=align_on, stack_methode=stack_methode)
  File "/home/someone/als/stack.py", line 158, in stack_live
    raise ValueError("fit format not support")
ValueError: fit format not support

What is going on?

**Comment by deufrai** [comment]
Hi and thank you for this report.

I am assuming you were running the code from the 'master' branch. Please be kind enough to try again, but with the 'alpha' branch. It contains the latest stable-enough code and fixes.

Awaiting your feedback

Thanks again

**Comment by kbahey** [comment]
Since alpha is the branch that should be installed, then please change the default branch displayed when users visit Github to be Alpha. 

That way future users will not make the mistake I did, and the instructions will be per the branch that needs to be used by most users. It will also lessens the support load on the development team. 

When I cloned the repository, and switched to alpha, using this:
```
git checkout alpha
```
After that I modified the copyfits.sh to use ~ instead of /home/gilles, but still got this error on every image:

```
ValueError: operands could not be broadcast together with shapes (2,2,976) (2,976,1304) 
```

**Comment by deufrai** [comment]
hi again and thanks for coming back to us
We know, documentation is not the best side of this project, so far. But we'll soon put strong efforts into it.

The issue you mention "operands could not be broadcast together with shapes (2,2,976) (2,976,1304)" has been encountered recently and seems to have been introduced by one of our dependencies being updated a few days ago.

If you are familiar with python's venv : create one and install our dependencies with their validated versions by using the requirements.txt provided with the sources.
Otherwise, use the venv_setup.sh and then simply launch the app with 
`python als.py`

Once again, thanks for your patience wrt the outdated docs and happy testing :)

**Comment by kbahey** [comment]
Until the documentation is better, please make alpha the default landing page for the github project. It will make your support load less.

I will try venv.

Found another error scrolling back:

OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/imgproc/src/color.cpp, line 9716
Traceback (most recent call last):
  File "/home/someone/als/als.py", line 197, in <lambda>
    align_on, save_on, stack_methode))
  File "/home/someone/als/code_utilities.py", line 24, in wrapped
    result = func(*args, **kwargs)
  File "/home/someone/als/als.py", line 296, in created
    image_type=save_type)
  File "/home/someone/als/code_utilities.py", line 24, in wrapped
    result = func(*args, **kwargs)
  File "/home/someone/als/preprocess.py", line 195, in save_tiff
    new_stack_image = cv2.cvtColor(new_stack_image, cv2.COLOR_RGB2BGR)
cv2.error: /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/imgproc/src/color.cpp:9716: error: (-215) scn == 3 || scn == 4 in function cvtColor

**Comment by kbahey** [comment]
The venv solution works. You can ignore the error in my last comment.
