### ISSUE TITLE
Task: make alpha the default branch

### ISSUE THREAD

**Issue by kbahey** [gehelem/als#41]
When I first came to this project, I downloaded the master branch, simply because it is the default one. 

Upon encountering errors, and opening an issue, I was instructed to use the alpha branch.

In order to avoid user confusion, and reduce the support load on the dev team, please make alpha the default branch on Github.

**Comment by deufrai** [comment]
I'd rather release a first stable version very soon
That would imply 
- merge alpha to master ( with datastore.VERSION updated to v0.1)
- tag that merge as v0.1
- fast-forward the develop branch to master
- update datastore.VERSION to v0.2-dev on develop
- continue our next development effort on the develop branch and let alpha die after some time

**Comment by kbahey** [comment]
I don't mind whichever process the devs agree upon, provided it makes the default page on Github work, rather than finding out that this is not the branch that should be used (like I found out the hard way).

The present alpha branch works for me, but only when I used venv. Otherwise, there were issues caused by dependencies. 

I have created a pull request with modifications to the README.md file to make venv the preferred method (since it will be the least problematic for users).

If you merge that into alpha, then do what you said above, then make v0.1 the default on the Github project page, users will get the advocated 'stable' (or 'released') version.

**Comment by deufrai** [comment]
Hi again
We managed to identify 5 past milestones and have properly released them. master branch is now our stable reference. v0.5 has been put there a few days ago.

alpha branch has been deleted, as we are coming closer to a regular dev/release workflow

So I'm closing this issue and encourage you to check what the next release ( version 0.6 currently developed on the 'develop') will look like.

We expect to see v0.6 to be released in 2 weeks tops.

The repo's default branch will then have all needed info for proper ALS install / use.

Thanks for your time and efforts

**Comment by kbahey** [comment]
I think my point was missed: when someone goes to /gehelem/als, they end up on the master branch, they download/clone it, and then it does not work. 

So, whatever branch that is a) known to be working and b) continually maintained with care not to break, should be the branch that the project should default to when someone lands on the above URL.

**Comment by deufrai** [comment]
I See your point, @kbahey 
I'll amend the README on develop branch to make it clear that this is a "bleeding edge" branch, and we can then switch the default branch to where install and usage docs are up to date and provide an easy way to try ALS out

'develop' is a dev branch, but we keep is as crash/bug free as possible. Some syntax / lint and other checks are done on Travis to help us on that

Thanks again

**Comment by kbahey** [comment]
If develop is the 'usable' branch, then /gehelem/als should default to the develop branch too. That way when someone lands on the github page for the project, the clone/download link will give them a usable snapshot.

**Comment by deufrai** [comment]
Default branch is now 'develop'. 
latest developments are there. Quite stable, with completed README

**Comment by gnthibault** [comment]
Thank you @deufrai  for all this work !

**Comment by kbahey** [comment]
Excellent! That gives people something working from what they land on.
