### ISSUE TITLE
Add server feature

### ISSUE THREAD

**Issue by dragonlost** [gehelem/als#7]
Need code server for see stack picture in live by other.

**Comment by gnthibault** [comment]
Found a very simple example here: https://www.reddit.com/r/learnpython/comments/1sendp/display_image_on_browser_using_python_http_server/

class MyHandler(http.server.SimpleHTTPRequestHandler):
    
img = open('ok.jpg', 'rb')
statinfo = os.stat('ok.jpg')
img_size = statinfo.st_size
print(img_size)

def do_HEAD(self):
    self.send_response(200)
    self.send_header("Content-type", "image/jpg")
    self.send_header("Content-length", img_size)
    self.end_headers()
    
def do_GET(self):
    self.send_response(200)
    self.send_header("Content-type", "image/jpg")
    self.send_header("Content-length", img_size)
    self.end_headers() 
    f = open('ok.jpg', 'rb')
    self.wfile.write(f.read())
    f.close()         
    
class MyServer(socketserver.ThreadingMixIn, socketserver.TCPServer):
    def __init__(self, server_adress, RequestHandlerClass):
        self.allow_reuse_address = True
        socketserver.TCPServer.__init__(self, server_adress, RequestHandlerClass, False)
        
if __name__ == "__main__":
    HOST, PORT = "localhost", 9999
    server = MyServer((HOST, PORT), MyHandler)
    server.server_bind()
    server.server_activate()
    server_thread = threading.Thread(target=server.serve_forever)
    server_thread.start()

**Comment by gehelem** [comment]
test message

**Comment by deufrai** [comment]
Let's consider it basically done
Will be improved in other issues
