### ISSUE TITLE
New keyboard shorcut : "i" to hide/show all controls

### ISSUE THREAD

**Issue by gehelem** [gehelem/als#78]
Having a keyboard shortcut to hide and show every control 
i humbly suggest i = L+P+B
Two possibilities, refering to Ms Michu's use case :
-  keep in memory what has been hiden to be able to revert 
-  that this shortcut would be just a "show all" / "hide all"

**Comment by deufrai** [comment]
This will be "maximize image"

**Comment by deufrai** [comment]
And we'll remember what dock(s) to show when "maximize image" is disabled

**Comment by deufrai** [comment]
Done
