### ISSUE TITLE
IndexError: index 2 is out of bounds for axis 0 with size 2 Abort trap: 6 on macOS Catalina

### ISSUE THREAD

**Issue by cliff-z** [gehelem/als#87]
First time actually on Github so hope this is ok,

This is the error I get when Align button is set and stacking the sample images in the repository.

The other error I put up on Youtube appears with my own Fits image stacking will send it too!

Traceback (most recent call last):
  File "/Users/cliffs/als/src/als/code_utilities.py", line 33, in wrapped
    result = func(*args, **kwargs)
  File "/Users/cliffs/als/src/als/processing.py", line 445, in run
    self._handle_image(image)
  File "/Users/cliffs/als/src/als/code_utilities.py", line 33, in wrapped
    result = func(*args, **kwargs)
  File "/Users/cliffs/als/src/als/processing.py", line 477, in _handle_image
    image = processor.process_image(image)
  File "/Users/cliffs/als/src/als/code_utilities.py", line 33, in wrapped
    result = func(*args, **kwargs)
  File "/Users/cliffs/als/src/als/processing.py", line 223, in process_image
    image.data[channel] = chosen_stretch(image.data[channel])
IndexError: index 2 is out of bounds for axis 0 with size 2
Abort trap: 6

Output og pip freeze

(venv) MacBook-Pro:als cliffs$ pip freeze
alabaster==0.7.12
-e git+https://github.com/gehelem/als.git@40ccd0c1924f72b7ade3d852e21fe05b588bccd2#egg=als
argh==0.26.2
astroalign==2.0.1
astroid==2.3.3
astropy==3.2.3
atomicwrites==1.3.0
attrs==19.3.0
Babel==2.7.0
certifi==2019.9.11
chardet==3.0.4
coverage==4.5.4
cycler==0.10.0
decorator==4.4.1
docutils==0.15.2
dtcwt==0.12.0
idna==2.8
imageio==2.6.1
imagesize==1.1.0
importlib-metadata==0.23
isort==4.3.21
Jinja2==2.10.3
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
llvmlite==0.30.0
MarkupSafe==1.1.1
matplotlib==3.1.1
mccabe==0.6.1
more-itertools==7.2.0
networkx==2.4
numba==0.46.0
numpy==1.17.4
opencv-python==4.1.1.26
packaging==19.2
pandas==0.25.3
pathtools==0.1.2
Pillow==6.2.1
pluggy==0.13.0
psutil==5.6.5
py==1.8.0
Pygments==2.4.2
pylint==2.4.4
pyparsing==2.4.5
PyQt5==5.13.2
PyQt5-sip==12.7.0
pytest==5.2.4
pytest-cov==2.8.1
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
pywi==0.3.dev12
PyYAML==5.1.2
qimage2ndarray==1.8
rawpy==0.13.1
requests==2.22.0
scikit-image==0.16.2
scipy==1.3.2
sep==1.0.3
six==1.13.0
snowballstemmer==2.0.0
Sphinx==2.2.1
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
typed-ast==1.4.0
urllib3==1.25.7
watchdog==0.9.0
wcwidth==0.1.7
wrapt==1.11.2
zipp==0.6.0

**Comment by deufrai** [comment]
Hi and thanks for the report
You are running the code as it is on the 'develop' branch, right ?

I notice your venv has many libraries with higher versions than what is in our requirements.txt

Can you describe how you got those libraries ?
Did you use `$ pip install -r requirements.txt` or any other way ?

**Comment by deufrai** [comment]
side note : This crash occurs while post-processing image

**Comment by cliff-z** [comment]
Yes I used git to get the develop branch , 
I just used pip to install each item in the requirements.txt not sure I can specify versions ?
No crashes if Align is not selected!

**Comment by deufrai** [comment]
to make sure you get the correct versions for each library, please :

1. deactivate your current venv
2. ditch it
3. recreate it
4. activate it
5. use the following command to get the specified versions : `$pip install -r requirements.txt`

**Comment by cliff-z** [comment]
Ok will try that thanks, I have it running on Linux Mint 19.2 Bionic but would like to get it going on my MacBook Pro.

**Comment by deufrai** [comment]
Sure
As long as you get the right lib versions, it should run just fine
And it would be nice to have a confirmation of ALS working on OSX

**Comment by cliff-z** [comment]
Might be ok now, have it processing  and aligning 70  Fits files from the ZWO178mc, a bit slow 

I ended up not ditching the venv as I would have had to reinstall python etc, 

Just entered the pip install -r requirements.txt command and it seemed to replace the existing ones. So far so good.
Cliff

**Comment by deufrai** [comment]
Nice to hear
Please report back if all works for you with the corrected dependencies versions.

Regarding performance : please post your machine's CPU and RAM specs and the log file names 'als.log' written in ALS root folder

**Comment by cliff-z** [comment]
No crash processed the whole batch ok. 6.4mb each.
When quit returns error code 0 thats good.
My machine is a 2015 MacBook Pro 13" with 3.1ghz I7 dual core with 16gb ram.
[als.log](https://github.com/gehelem/als/files/3866195/als.log)

pip freeze now:

alabaster==0.7.12
-e git+https://github.com/gehelem/als.git@40ccd0c1924f72b7ade3d852e21fe05b588bccd2#egg=als
argh==0.26.2
astroalign==1.0.4
astroid==2.3.3
astropy==3.2.1
atomicwrites==1.3.0
attrs==19.3.0
Babel==2.7.0
certifi==2019.9.11
chardet==3.0.4
coverage==4.5.4
cycler==0.10.0
decorator==4.4.1
docutils==0.15.2
dtcwt==0.12.0
idna==2.8
imageio==2.6.1
imagesize==1.1.0
importlib-metadata==0.23
isort==4.3.21
Jinja2==2.10.3
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
llvmlite==0.30.0
MarkupSafe==1.1.1
matplotlib==3.1.1
mccabe==0.6.1
more-itertools==7.2.0
networkx==2.4
numba==0.45.1
numpy==1.16.4
opencv-python==4.1.0.25
packaging==19.2
pandas==0.25.3
pathtools==0.1.2
Pillow==6.2.1
pluggy==0.13.0
psutil==5.6.5
py==1.8.0
Pygments==2.4.2
pylint==2.3.1
pyparsing==2.4.5
PyQt5==5.13.0
PyQt5-sip==12.7.0
pytest==5.1.2
pytest-cov==2.7.1
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
pywi==0.3.dev12
PyYAML==5.1.2
qimage2ndarray==1.8
rawpy==0.13.1
requests==2.22.0
scikit-image==0.16.2
scipy==1.3.2
sep==1.0.3
six==1.13.0
snowballstemmer==2.0.0
Sphinx==2.2.0
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
typed-ast==1.4.0
urllib3==1.25.7
watchdog==0.9.0
wcwidth==0.1.7
wrapt==1.11.2
zipp==0.6.0

**Comment by cliff-z** [comment]
Just tried it with the 5 sample M13 images in the repository was very quick indeed may be the fact I use  Alt/Az makes it work harder?

**Comment by deufrai** [comment]
those samples are B&W and small. No wonder it runs faster :)

I had a look at your log file : The bottleneck is clearly image alignment, here. Otherwise, other processes are on par with expected perfs.

I suggest you close Issues #87 & #88 and open a new one regarding perfs.

Image alignment is coded to take advantage of mutli-core CPUs, but we'll need debug logs to further analyze how stacking is done on your machine.
So please make sure you switch ON 'debug logs' in the preferences, restart ALS and stack just a few frames, as detailed logs produce around 100kB of data per stacked image.

Thanks again

**Comment by cliff-z** [comment]
Many thanks for your help, looking promising.

Will close out these two issues as you request.
