### ISSUE TITLE
ValueError: could not broadcast input array from shape (2,2080,3096) into shape (2080,3096) Abort trap: 6 on macOS Catalina

### ISSUE THREAD

**Issue by cliff-z** [gehelem/als#88]
Ok this is the other crash I get on macOS Catalina, using my own Fits files. I use a Alt-Az mount but Sharpcap and AstroliveUSB work ok.

I seem to get crashes only when Align is selected but thats what we want ?

Without Align Selected no crashes.

ValueError: could not broadcast input array from shape (2,2080,3096) into shape (2080,3096)
Abort trap: 6
 
Traceback (most recent call last):
  File "/Users/cliffs/als/src/als/code_utilities.py", line 33, in wrapped
    result = func(*args, **kwargs)
  File "/Users/cliffs/als/src/als/processing.py", line 445, in run
    self._handle_image(image)
  File "/Users/cliffs/als/src/als/code_utilities.py", line 33, in wrapped
    result = func(*args, **kwargs)
  File "/Users/cliffs/als/src/als/stack.py", line 173, in _handle_image
    self._align_image(image)
  File "/Users/cliffs/als/src/als/code_utilities.py", line 33, in wrapped
    result = func(*args, **kwargs)
  File "/Users/cliffs/als/src/als/stack.py", line 204, in _align_image
    self._apply_transformation(image, transformation)
  File "/Users/cliffs/als/src/als/code_utilities.py", line 33, in wrapped
    result = func(*args, **kwargs)
  File "/Users/cliffs/als/src/als/stack.py", line 247, in _apply_transformation
    image.data[channel] = data
ValueError: could not broadcast input array from shape (2,2080,3096) into shape (2080,3096)
Abort trap: 6
alabaster==0.7.12
-e git+https://github.com/gehelem/als.git@40ccd0c1924f72b7ade3d852e21fe05b588bccd2#egg=als
argh==0.26.2
astroalign==2.0.1
astroid==2.3.3
astropy==3.2.3
atomicwrites==1.3.0
attrs==19.3.0
Babel==2.7.0
certifi==2019.9.11
chardet==3.0.4
coverage==4.5.4
cycler==0.10.0
decorator==4.4.1
docutils==0.15.2
dtcwt==0.12.0
idna==2.8
imageio==2.6.1
imagesize==1.1.0
importlib-metadata==0.23
isort==4.3.21
Jinja2==2.10.3
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
llvmlite==0.30.0
MarkupSafe==1.1.1
matplotlib==3.1.1
mccabe==0.6.1
more-itertools==7.2.0
networkx==2.4
numba==0.46.0
numpy==1.17.4
opencv-python==4.1.1.26
packaging==19.2
pandas==0.25.3
pathtools==0.1.2
Pillow==6.2.1
pluggy==0.13.0
psutil==5.6.5
py==1.8.0
Pygments==2.4.2
pylint==2.4.4
pyparsing==2.4.5
PyQt5==5.13.2
PyQt5-sip==12.7.0
pytest==5.2.4
pytest-cov==2.8.1
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
pywi==0.3.dev12
PyYAML==5.1.2
qimage2ndarray==1.8
rawpy==0.13.1
requests==2.22.0
scikit-image==0.16.2
scipy==1.3.2
sep==1.0.3
six==1.13.0
snowballstemmer==2.0.0
Sphinx==2.2.1
sphinx-rtd-theme==0.4.3
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
typed-ast==1.4.0
urllib3==1.25.7
watchdog==0.9.0
wcwidth==0.1.7
wrapt==1.11.2
zipp==0.6.0
pip freeze output;

**Comment by deufrai** [comment]
Hi again

Indeed, this crash occurs while aligning.
Same observation as in Issue #87 : I suspect trouble from the Numpy version you are using.
I recall having the very same error when using most recent numpy versions, that's we downgraded it in requirements.txt

Same question, then : how did you get the libraries into your venv ?

**Comment by cliff-z** [comment]
There is a system called home-brew on macOS together with Xcode command line utilities.
So brew install python for example

**Comment by deufrai** [comment]
Fixed by user : force dependencies versions as defined in requirements.txt
