### ISSUE TITLE
Could not start web server : [Errno 48] Address already in use

### ISSUE THREAD

**Issue by cliff-z** [gehelem/als#90]
Well looks like I broke the web server on my macOS version of ALS while the rest is working ok?

2019-11-20 12:16:43,960 MainThread   als.logic            ERROR    Could not start web server : [Errno 48] Address already in use

**Comment by cliff-z** [comment]
Fixed by removing all running python processes and restarting als now works fine.

**Comment by deufrai** [comment]
Hi
When this happened, was ALS launched after a previous crash ?

**Comment by cliff-z** [comment]
Not sure but most probably hasn't happened since. Had it working really well today on simulated images from a program called Astroimager and also tried EKOS no crashes at all. 
Nothing but cloud so no live images possible.

**Comment by deufrai** [comment]
Will try and reproduce, then add a check on startup so we can kill any remaining server from a previous crash

**Comment by cliff-z** [comment]
Thanks I will close this issue now
