### ISSUE TITLE
Perte données et bureau

### ISSUE THREAD

**Issue by rmor51** [gehelem/als#97]
Voulant tester ALS et simuler l'arrivée de photos dans un répertoire, j'ai lancé en sudo le script copy.sample.sh du répertoire "utils" de ALS. Bien mal m'en a pris ! J'ai perdu TOUTES mes données du répertoire home. 
Sur le deuxième disque DATA, bon nombres de répertoires ont disparu, et sur ceux restant, certains sont vides, d'autres en parti.

HELP !

**Comment by gehelem** [comment]
est-ce que tu peux essayer de nous donner les arguments que tu as utilisés pour lancer le script ?

**Comment by rmor51** [comment]
sudo copy.sample.sh

**Comment by deufrai** [comment]
hello
pour que l'on puisse comprendre ce qui s'est passé **(par contre, pour récupérer tes fichiers, c'est bien maheureusement hors de notre portée)** nous avons besoin de connaître les arguments que tu as passés au script.

parce que, sudo ou non, si tu invoques le script (tel que sur la branche develop) sans aucun argument, le script arrête son exécution avant de purger quoi que ce soit. Je viens de faire l'essai à l'instant

```
$ sudo utils/copy_samples.sh
Missing argument : target scan folder
Aborting...
```

et au passage, le script `copy.sample.sh` n'existe pas ;)

**Comment by rmor51** [comment]
Aucun argument. Et je me suis retrouvé sur un bureau tout neuf.

**Comment by rmor51** [comment]
Pour les données ça semble râpé. Rien avec testdisk. J'ai une sauvegarde pas trop vieille de mon répertoire home. Je vais repartir là dessus.

**Comment by deufrai** [comment]
Hello @rmor51 

Vraiment désolé de cette perte de données :(

Il est impossible que le script en question ait poursuivi son exécution si aucun argument n'a été passé. Mais comme tu as perdu tes données et donc aussi sûrement l'historique de tes commandes, je pense que nous n'aurons malheureusement pas le fin mot de cette affaire...

Quoi qu'il en soit, pour être certain que cette mésaventure de ne reproduise pas, une modif a été apportée au script. Voir commit fe27bb4

Le répertoire de destination (qui est l'argument attendu) n'est plus purgé et si le script écrase maintenant tout fichier existant déjà dans le dossier de destination

**Comment by rmor51** [comment]
Merci. Je suis en cours de ré install. Je ne devrais pas perdre beaucoup de données avec ma sauvegarde. Mon portable me sert surtout pour l'astro, très peu pour autre chose.
