### ISSUE TITLE
erreur pendant install sur rpi

### ISSUE THREAD

**Issue by sergio49** [gehelem/als#99]
Bonjour,
en installant la verson 6.0.1 sur un raspberry pi avec raspbian buster, lors de l'éxécution de la commande "./utils/venv_setup.sh", j'ai l'erreur suivante : 
ERROR: Could not find a version that satisfies the requirement PyQt5==5.13.0 (from -r /home/pi/als/requirements.txt (line 6)) (from versions: 5.14.0, 5.14.1, 5.14.2)
ERROR: No matching distribution found for PyQt5==5.13.0 (from -r /home/pi/als/requirements.txt (line 6))

**Comment by deufrai** [comment]
Hello et merci pour ce retour

L'installation sur rpi est encore un peu particulière.

Ci-dessous, la liste des actions à mener pour une install sur RPI4 / RaspBian Buster.

`$ sudo apt-get install python3-opencv python3-pyqt5 libraw-dev llvm pyqt5-dev-tools libatlas-base-dev libjpeg-dev
$ git clone https://github.com/gehelem/als.git
$ cd als
$ python3 -m venv --system-site-packages venv
$ source venv/bin/activate
$ pip install --upgrade pip
# IMPORTANT : Enlever les 2 lignes concernant pyqt5 et opencv dans requirements.txt
$ pip install -I -r requirements.txt
$ python setup.py develop
$ als`

Cette procédure sera ajoutée à la documentation des prochaines versions

Tiens-nous au courant de tes résultats

**Comment by sergio49** [comment]
Bonjour,
L'installation s'est déroulée sans problème, tout à l'air ok.
Merci pour la solution.
